name: "\U0001F41B Bug Report"
description: Report a bug in jAI-workflow. Please provide as much information as possible to help us reproduce the bug.
title: "[BUG] "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
        Use this to report BUGS in jAI Workflow. For usage questions and general design questions, please use [GitHub Discussions](https://github.com/czelabueno/jai-workflow/discussions).
  - type: checkboxes
    id: checks
    attributes:
      label: Checked other resources
      description: Before submitting this issue, please confirm that you have completed all the steps below by checking each option. These steps help ensure your issue is well-defined, relevant, and actionable.
      options:
        - label: This is a bug, not a usage question. For questions, please use GitHub Discussions.
          required: true
        - label: I added a clear and detailed title that summarizes the issue.
          required: true
        - label: I read what a minimal reproducible example is (https://stackoverflow.com/help/minimal-reproducible-example).
          required: true
        - label: I included a self-contained, minimal example that demonstrates the issue INCLUDING all the relevant imports. The code run AS IS to reproduce the issue.
          required: true
  - type: input
    id: title
    attributes:
      label: Bug Title
      description: A clear and concise title of what the bug is.
      placeholder: "Bug title"

  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
      placeholder: "Description of the bug"

  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: |
        Please add a self-contained, [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example) with your use case.
      placeholder: |
        import io.github.czelabueno.jai.workflow.DefaultStateWorkflow;
        import io.github.czelabueno.jai.workflow.StateWorkflow;
        import io.github.czelabueno.jai.workflow.node.Node;
        
        import static io.github.czelabueno.jai.workflow.WorkflowStateName.START;
        import static io.github.czelabueno.jai.workflow.WorkflowStateName.END;

        StateWorkflow jAiWorkflow = DefaultStateWorkflow.<MyStatefulBean>builder()
            .statefulBean(myStatefulBean)
            .addNodes(asList(node1, node2))
            .build();
        
        jAiWorkflow.putEdge(START, node1);
        jAiWorkflow.putEdge(node1, node2);
        jAiWorkflow.putEdge(node2, END);
        
        jAiWorkflow.run("Hello, World!");
      render: java

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: "Expected behavior"

  - type: textarea
    id: logs
    attributes:
      label: Logs and Stack Traces (if applicable)
      description: |
        If you are reporting an error, please include the full error message and stack trace.
      placeholder: |
        Exception + full stack trace
      render: shell

  - type: input
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide the following information:
        - jAI Workflow Core version: [e.g. 0.2.0]
        - jAI Workflow LangChain4j version : [e.g. 0.2.0]
        - Java version: [e.g. 21]
        - LangChain4j version (if applicable): [e.g. 1.0.0-alpha]
        - Spring Boot version (if applicable):
      placeholder: "Environment details"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: "Additional context"
