name: jAI Workflow CI

on:
  push:
      branches:
      - main
  pull_request:
      branches:
      - main

jobs:
  java_build:
    strategy:
      matrix:
          java_version: ['17', '21']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java_version }}
          distribution: 'temurin'
          cache: maven
      - name: Build and test with JDK ${{ matrix.java_version }}
        run: |
          mvn -B -U -T4C clean test \
            -Dmaven.javadoc.skip=true \
            -DskipITs=true surefire-report:report
      - name: Upload Surefire Reports with JDK ${{ matrix.java_version }}
        uses: actions/upload-artifact@v4
        with:
          name: test-surefire-reports-jdk-${{ matrix.java_version }}
          path: '**/target/surefire-reports/*.xml'
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/target/*-reports/TEST-*.xml'
          annotate_only: true


