name: jAI Workflow Release

on:
  push:
    tags:
      - v0.[0-9].[0-9]+
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Build and deploy to Maven Central
    if: github.repository == 'czelabueno/jai-workflow'
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
             java-version: '21'
             distribution: 'temurin'
             cache: maven
             server-id: ossrh
             server-username: OSSRH_USERNAME
             server-password: OSSRH_PASSWORD
             gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
             gpg-passphrase: GPG_PASSPHRASE
        - name: Publish to Sonatype Maven Central
          run: |
            mvn versions:set -DnewVersion=${GITHUB_REF#refs/tags/v}
            mvn -B -U --fail-at-end -Prelease clean deploy -DskipTests
          env:
             GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
             OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
             OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  create-github-release:
    name: Create GitHub Release
    needs: release
    runs-on: ubuntu-latest
    steps:
        - name: Create GitHub Release
          shell: bash
          env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             tag: ${{ github.ref_name }}
          run: |
            gh release create "$tag" \
              --repo "${{ github.repository }}" \
              --title "$tag" \
              --generate-notes \
              --latest
