name: release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
             java-version: '17'
             distribution: 'temurin'
             cache: maven
             server-id: ossrh
             server-username: OSSRH_USERNAME
             server-password: OSSRH_PASSWORD
             gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
             gpg-passphrase: GPG_PASSPHRASE

        - name: release
          run: mvn -B -Psign clean deploy -DskipTests
          env:
             GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
             OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
             OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        - name: tag the release
          run: |
            git tag -a v${{ steps.get_version.outputs.version }} -m "Release version v${{ steps.get_version.outputs.version }}"
            git push origin v${{ steps.get_version.outputs.version }}
