name: jAI Workflow Snapshot-release

on:
  workflow_dispatch:

jobs:
  snapshot-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
      - name: Publish SNAPSHOT to Sonatype (Maven Central)
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: |
          cat /home/runner/.m2/settings.xml
          mvn -B --fail-at-end \
            -DskipTests -DskipITs \
            clean deploy

